---
- hosts: localhost
  vars:
    KONG_ADMIN_URL: "http://127.0.0.1:8001"
    KONG_JWT: ""
  roles:
    - role: kong_service
      service:
        name: "testservice"
        url: "http://httpbin.org"
    - role: kong_route
      route:
        service_name: "testservice"
        paths:
          - "/foo/bar"
