---
- hosts: localhost
  vars:
    KONG_ADMIN_URL: "http://{{ IPADD }}:8001"
    KONG_JWT: ""
  roles:
    - role: kong_service
      service:
        name: "httpbin-service-get"
        url: "http://eu.httpbin.org/get"
    - role: kong_route
      route:
        service_name: "httpbin-service-get"
        hosts:
          - "examplehttpbin.com"
    - role: kong_plugins
      plugins:
        service_name: "httpbin-service-get"
        name:
          - "key-auth"
