---
- hosts: localhost
  vars:
    KONG_ADMIN_URL: "http://{{ IPADD }}/kongadmin"
    KONG_JWT: ""
  roles:
    - role: kong_service
      service:
        name: "httpbin-service-get"
        url: "http://eu.httpbin.org/get"
    - role: kong_route
      route:
        service_name: "httpbin-service-get"
        hosts:
          - "examplehttpbin.com"
    - role: kong_plugins
      plugins:
        service_name: "httpbin-service-get"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "httpbin-service-get"
        username: "Jason"
        plugins: "key-auth"
        key: "1234"
  # custom
  
    - role: kong_service
      service:
        name: "spring"
        url: "http://{{ IPADD }}:30500/api/user"
    - role: kong_route
      route:
        service_name: "spring"
        hosts:
          - "examplespring.com"
    - role: kong_plugins
      plugins:
        service_name: "spring"
        name: "key-auth"
    - role: kong_consumer
      consumer:
        service_name: "spring"
        username: "apring"
        plugins: "key-auth"
        key: "1234"
    
