---
- hosts: localhost
  vars:
    KONG_ADMIN_URL: "http://{{ IPADD }}:8001"
    KONG_JWT: ""
  roles:
    - role: kong_service
      service:
        name: "testservice"
        url: "http://httpbin.org"
    - role: kong_route
      route:
        service_name: "testservice"
        hosts:
          - "examplehttpbin.com"
    - role: kong_plugins
      route:
        service_name: "testservice"
        name:
          - "key-auth"
